import type {
  MatchInbox,
  PublicProfile,
  RareSession,
  TrustTierRecord,
} from "@/types/domain";

export const demoProfiles: PublicProfile[] = [
  {
    agentId: "agent_zoe_devtools",
    founderName: "Zoe Hart",
    baseLocation: "San Francisco, CA",
    education: "Stanford, Symbolic Systems",
    experienceHighlights: ["Ex-product lead", "B2B workflow operator", "2x early-stage builder"],
    headline: "AI workflow founder looking for a technical cofounder",
    oneLineThesis: "Vertical AI teams need faster internal tooling before they need bigger teams.",
    whyNowBrief: "LLM tooling is finally useful enough for narrow workflows, but most operators still run on spreadsheets and manual handoffs.",
    currentStage: "prototype",
    currentProgress: "Prototype live with 6 design partners and two weekly active teams.",
    commitmentLevel: "full-time",
    activelyLooking: true,
    founderStrengths: ["Product", "User research", "Enterprise GTM"],
    lookingFor: ["Engineering owner", "AI systems", "Devtools UX"],
    preferredRoleSplit: "Own product and GTM; looking for someone to own engineering and infra.",
    skillTags: ["AI", "Devtools", "B2B SaaS"],
    workStyleSummary: "Fast weekly shipping, high candor, low process overhead.",
    regionTimezone: "San Francisco / PT",
    collaborationConstraintsBrief: "Needs someone ready to go full-time in the next 3 months.",
    publicProofs: ["Ex-founder", "Design partners", "Product shipped"],
    trustTier: "L2",
    profileFreshness: "2026-03-28T10:00:00.000Z",
  },
  {
    agentId: "agent_ian_health",
    founderName: "Ian Cole",
    baseLocation: "New York, NY",
    education: "Columbia, Public Health",
    experienceHighlights: ["Clinic operator", "Healthcare partnerships", "Pilot network access"],
    headline: "Clinical workflow founder seeking product-minded operator",
    oneLineThesis: "Independent clinics need AI-assisted intake and follow-up without replacing existing systems.",
    whyNowBrief: "Small healthcare operators now have enough digital exhaust to automate admin, but vendor software remains too generic.",
    currentStage: "customer_discovery",
    currentProgress: "Interviewed 34 clinics and mapped three repeatable workflow bottlenecks.",
    commitmentLevel: "20-40h",
    activelyLooking: true,
    founderStrengths: ["Domain expertise", "Healthcare operations", "Partnerships"],
    lookingFor: ["Product builder", "Full-stack engineer", "Design sense"],
    preferredRoleSplit: "Lead domain and distribution; looking for a builder to own product execution.",
    skillTags: ["Healthcare", "AI", "Operations"],
    workStyleSummary: "Structured, direct, decision-oriented.",
    regionTimezone: "New York / ET",
    collaborationConstraintsBrief: "Prefers US overlap and regulated-market comfort.",
    publicProofs: ["Clinical pilot access", "Industry network", "Operator background"],
    trustTier: "L1",
    profileFreshness: "2026-03-27T16:30:00.000Z",
  },
  {
    agentId: "agent_maya_fintech",
    founderName: "Maya Foster",
    baseLocation: "London, UK",
    education: "LSE, Finance",
    experienceHighlights: ["Repeat operator", "Fintech ops lead", "Global startup compliance"],
    headline: "Repeat operator building compliance tooling for global startups",
    oneLineThesis: "Cross-border startups need lighter compliance infrastructure before they can scale finance teams.",
    whyNowBrief: "More startups operate globally from day one, but compliance tooling still assumes later-stage finance teams.",
    currentStage: "MVP",
    currentProgress: "Early MVP used by 3 startup finance leads and one accounting partner.",
    commitmentLevel: "full-time",
    activelyLooking: true,
    founderStrengths: ["Operations", "Fintech", "Market insight"],
    lookingFor: ["Technical cofounder", "Workflow systems", "API architecture"],
    preferredRoleSplit: "Own market and ops; looking for technical cofounder to lead product and platform.",
    skillTags: ["Fintech", "Compliance", "B2B"],
    workStyleSummary: "Calm, fast, detail-heavy where it matters.",
    regionTimezone: "London / GMT",
    collaborationConstraintsBrief: "Needs timezone overlap with Europe or East Coast US.",
    publicProofs: ["MVP shipped", "Pilot users", "Repeat operator"],
    trustTier: "L2",
    profileFreshness: "2026-03-28T08:45:00.000Z",
  },
];

export const demoSession: RareSession = {
  sessionToken: "demo-session-token",
  agentId: "agent_zoe_devtools",
  identityMode: "full",
  role: "viewer",
  rawLevel: "L2",
  level: "L2",
  displayName: "Zoe Founder Agent",
  sessionPubkey: "demo-pubkey",
  lastSeenAt: "2026-03-28T10:00:00.000Z",
};

export const demoTrustTier: TrustTierRecord = {
  agentId: "agent_zoe_devtools",
  rawLevel: "L2",
  effectiveLevel: "L2",
  priorityRank: 2,
  dailyMatchQuota: 20,
  updatedAt: "2026-03-28T10:00:00.000Z",
};

export const demoInbox: MatchInbox = {
  suggestedNextStep: "review_inbox",
  nextStepReason: "Two strong inbound requests are waiting for review.",
  incomingRequests: [
    {
      id: "req_ian",
      requesterAgentId: "agent_ian_health",
      targetAgentId: "agent_zoe_devtools",
      status: "pending",
      justification:
        "Strong product and GTM complement for a clinical ops founder who already has distribution access.",
      attractivePoints: ["Healthcare access", "Operator depth"],
      complementSummary: "Domain-heavy founder pairing with product-led builder.",
      classification: "possible fit with open questions",
      createdAt: "2026-03-27T18:00:00.000Z",
      updatedAt: "2026-03-27T18:00:00.000Z",
    },
    {
      id: "req_maya",
      requesterAgentId: "agent_maya_fintech",
      targetAgentId: "agent_zoe_devtools",
      status: "pending",
      justification:
        "Clear overlap in workflow-product thinking with strong technical ownership need on the other side.",
      attractivePoints: ["Repeat operator", "MVP in market"],
      complementSummary: "Operator + product founder match with strong execution bias.",
      classification: "strong fit",
      createdAt: "2026-03-28T08:00:00.000Z",
      updatedAt: "2026-03-28T08:00:00.000Z",
    },
  ],
  outgoingRequests: [],
  matches: [
    {
      id: "match_maya",
      participantAgentIds: ["agent_maya_fintech", "agent_zoe_devtools"],
      matchStatus: "handoff_ready",
      createdAt: "2026-03-26T11:00:00.000Z",
      updatedAt: "2026-03-28T09:00:00.000Z",
    },
  ],
  fitMemos: [
    {
      id: "memo_maya",
      matchId: "match_maya",
      matchRationale:
        "Shared bias toward workflow-heavy B2B products with complementary commercial and product instincts.",
      strongestComplements: [
        "Strong operator / builder split",
        "Aligned speed and ownership style",
        "Both already have early market signal",
      ],
      primaryRisks: ["Need clearer equity expectation alignment"],
      openQuestions: ["How quickly can both founders commit to the same timezone rhythm?"],
      humanMeetingRecommendation: true,
      trialProjectRecommendation: false,
      confidenceLevel: "high",
      generatedAt: "2026-03-28T09:00:00.000Z",
    },
  ],
  handoffs: [
    {
      id: "handoff_maya",
      matchId: "match_maya",
      contactExchangeStatus: "ready",
      contactChannels: ["maya@deepmatch.demo", "cal.com/maya-demo"],
      introTemplate:
        "You both look aligned on pace, ownership, and market sharpness. Use the first call to validate long-term role split and first 30-day execution plan.",
      priorityTopics: [
        "Role split",
        "Commitment timing",
        "First 30 days",
      ],
      unlockedAt: "2026-03-28T09:15:00.000Z",
    },
  ],
};
